#!/bin/bash
input="$(pwd)/$1"
export PUML_G_OUTPUT="$(pwd)/$2"
fswatch -0 "$input" | xargs -0 -I{} puml generate "{}" -o "$PUML_G_OUTPUT" &
fswatch -0 "$PUML_G_OUTPUT" | xargs -0 -I{} imgcat "{}" &
 
